name: WattLeft
options:
  deploymentTarget:
    macOS: "15.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.wattleft.app
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "6.0"
    INFOPLIST_KEY_LSUIElement: YES
    INFOPLIST_KEY_NSHighResolutionCapable: YES

schemes:
  WattLeft:
    build:
      targets:
        WattLeft: all
    test:
      targets:
        - WattLeftTests

targets:
  WattLeft:
    type: application
    platform: macOS
    sources:
      - path: WattLeft/App
      - path: WattLeft/App/MenuBarDisplayMode.swift
    resources:
      - path: WattLeft/App/Resources
    settings:
      base:
        INFOPLIST_KEY_CFBundleDisplayName: WattLeft
        INFOPLIST_KEY_CFBundleName: WattLeft
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.utilities
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES

  WattLeftTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: WattLeft/Tests
    dependencies:
      - target: WattLeft
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
